### ISSUE TITLE
Installation error in zoxide release 0.7.6

### ISSUE THREAD

**Issue by rinshadka** [nyrst/asdf-zoxide#2]
`asdf install zoxide latest`

Downloading zoxide release 0.7.6...
curl: (22) The requested URL returned error: 404
asdf-zoxide: Could not download https://github.com/ajeetdsouza/zoxide/releases/download/v0.7.6/zoxide-x86_64-unknown-linux-musl.tar.gz
asdf-zoxide: An error ocurred while installing zoxide 0.7.6.

Actually the asset link changed in this zoxide release. Asset is available in below links:- 

https://github.com/ajeetdsouza/zoxide/releases/download/v0.7.6/zoxide-v0.7.6-x86_64-unknown-linux-musl.tar.gz

**Comment by epoweripione** [comment]
Same error in zoxide 0.7.8, pls fix it:
https://github.com/ajeetdsouza/zoxide/releases/download/v0.7.8/zoxide-v0.7.8-x86_64-unknown-linux-musl.tar.gz

**Comment by SiegfriedEhret** [comment]
Fixed in https://github.com/nyrst/asdf-zoxide/pull/3, thanks @rinshadka
