### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by iwataka** [nyrst/asdf-zoxide#6]
Currently this plugin doesn't seem to support macOS.
On my macOS (12.3 Monterey), when I installed zoxide via this plugin, I encountered the following error.

```sh
$ zoxide --help
/Users/takatoshiiwasa/.asdf/lib/commands/command-exec.bash: line 28: /Users/takatoshiiwasa/.asdf/installs/zoxide/0.8.0/bin/zoxide: cannot execute binary file: Exec format error
/Users/takatoshiiwasa/.asdf/lib/commands/command-exec.bash: line 28: /Users/takatoshiiwasa/.asdf/installs/zoxide/0.8.0/bin/zoxide: Undefined error: 0
```

I guess this error is caused by the following lines, that installs linux version even on macOS.

https://github.com/nyrst/asdf-zoxide/blob/main/lib/utils.bash#L41-L51

Is there any plan to support (or can I create PR) ?

**Comment by SiegfriedEhret** [comment]
Hello! Thanks for reaching out.

Please don't hesitate to make a PR, thanks!
